In [1]:
### Tensorflow > 2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### Sentences
sent =['the glass of milk',
       'the glass of juice',
       'the cup of tea',
       'I am a good boy',
       'I am a good Developer',
       'Understand the meaning of words',
       'Your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good Developer',
 'Understand the meaning of words',
 'Your videos are good']

In [4]:
# Setting the vocabulary size
voc_size = 10000

# One Hot Representation

In [5]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[7758, 3263, 7790, 8823], [7758, 3263, 7790, 6924], [7758, 849, 7790, 4928], [2302, 704, 5896, 7133, 3835], [2302, 704, 5896, 7133, 8706], [3235, 7758, 2122, 7790, 7299], [2062, 8262, 9986, 7133]]


# Word Embedding Representation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences # to make the size of sequences same to create a good embedding representation
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [10]:
sent_length = 8 # The length that each sentence must be.
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen= sent_length)
# The pre parameter add 0's to the front of each sentence to match sent_length
print(embedded_docs)

[[   0    0    0    0 7758 3263 7790 8823]
 [   0    0    0    0 7758 3263 7790 6924]
 [   0    0    0    0 7758  849 7790 4928]
 [   0    0    0 2302  704 5896 7133 3835]
 [   0    0    0 2302  704 5896 7133 8706]
 [   0    0    0 3235 7758 2122 7790 7299]
 [   0    0    0    0 2062 8262 9986 7133]]


In [11]:
dim=10

In [12]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

[[[-0.01142468 -0.03784895 -0.01040639 -0.04113906  0.00872464
    0.04556211  0.02771118  0.01823404 -0.04269209 -0.02533933]
  [-0.01142468 -0.03784895 -0.01040639 -0.04113906  0.00872464
    0.04556211  0.02771118  0.01823404 -0.04269209 -0.02533933]
  [-0.01142468 -0.03784895 -0.01040639 -0.04113906  0.00872464
    0.04556211  0.02771118  0.01823404 -0.04269209 -0.02533933]
  [-0.01142468 -0.03784895 -0.01040639 -0.04113906  0.00872464
    0.04556211  0.02771118  0.01823404 -0.04269209 -0.02533933]
  [ 0.00588556 -0.04343342  0.03794089  0.04360607 -0.02765521
   -0.01562198  0.00503638 -0.01395023  0.0018226  -0.01884951]
  [-0.00433926 -0.00630044 -0.04953232  0.03645525 -0.04925347
    0.03590101  0.0451285  -0.03737964  0.0135938  -0.03584465]
  [-0.02035377  0.01268368 -0.00372165  0.04197291  0.02426687
    0.00840374 -0.00037336 -0.01623069 -0.00467249 -0.00770698]
  [-0.01130787  0.03038811  0.02868981 -0.0348345  -0.01029314
   -0.04884185  0.0249348  -0.01022989 -0.045648

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 7758, 3263, 7790, 8823], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

array([[-0.01142468, -0.03784895, -0.01040639, -0.04113906,  0.00872464,
         0.04556211,  0.02771118,  0.01823404, -0.04269209, -0.02533933],
       [-0.01142468, -0.03784895, -0.01040639, -0.04113906,  0.00872464,
         0.04556211,  0.02771118,  0.01823404, -0.04269209, -0.02533933],
       [-0.01142468, -0.03784895, -0.01040639, -0.04113906,  0.00872464,
         0.04556211,  0.02771118,  0.01823404, -0.04269209, -0.02533933],
       [-0.01142468, -0.03784895, -0.01040639, -0.04113906,  0.00872464,
         0.04556211,  0.02771118,  0.01823404, -0.04269209, -0.02533933],
       [ 0.00588556, -0.04343342,  0.03794089,  0.04360607, -0.02765521,
        -0.01562198,  0.00503638, -0.01395023,  0.0018226 , -0.01884951],
       [-0.00433926, -0.00630044, -0.04953232,  0.03645525, -0.04925347,
         0.03590101,  0.0451285 , -0.03737964,  0.0135938 , -0.03584465],
       [-0.02035377,  0.01268368, -0.00372165,  0.04197291,  0.02426687,
         0.00840374, -0.00037336, -0.01623069

Ref Link : https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/